### ISSUE TITLE
Possible memory leak due to not closing the fits files

### ISSUE THREAD

**Issue by gully** [KeplerGO/k2-quality-control#4]
We see a `fits.open( )` but no `.close( )` in our brief search.  In any case the RAM is ramping up.
![screen shot 2017-06-02 at 2 40 14 pm](https://cloud.githubusercontent.com/assets/860227/26745858/6daa38a6-47a1-11e7-8e4d-0b16a62a0626.png)

**Comment by barentsen** [comment]
Oh dear, good find, I better start monitoring my memory in the same way!
